### ISSUE TITLE
error in intersect_rtree?  doesn't save first list

### ISSUE THREAD

**Issue by hwreeves-USGS** [aleaf/GIS_utils#4]
Andy - is there an issue with intersect_rtree?, it looks like the first list returned by the intersection isn't saved before the next intersection writes to the same vector.

       # test for intersection with bounding box of each polygon feature in geom2 using spatial index
        inds = [i for i in idx.intersection(poly.bounds)]
        # test each feature inside the bounding box for intersection with the polygon geometry
        inds = [i for i in inds if geom1[i].intersects(poly)]
        isfr.append(inds)

**Comment by aleaf** [comment]
The first step returns a list of indices in idx, the spatial index that Rtree created. These represent intersections with the bounding box of the feature in geom2 (rtree only works with bounding boxes).

Because we iterated over geom1 in building the spatial index, there is a one-to-one correspondence between the index numbers in the spatial index, and the index of the corresponding geometry in geom1.

The second step uses those indices to test each corresponding geometry in geom1 for intersection with the actual geometry of the polygon feature in geom2. Since the list returned by this step is based on actual intersections (instead of bounding boxes), this is the one we want; we can discard the first list.

Andy

**Comment by hwreeves-USGS** [comment]
tricky...
thanks, have a good weekend.

HWR

Howard W. Reeves
USGS Michigan Water Science Center
6520 Mercantile Way, Suite 5
Lansing, MI 48911-5991
517-887-8914
517-887-8937 (fax)
hwreeves@usgs.gov
